### ISSUE TITLE
Bean validation - Cross validation not working

### ISSUE THREAD

**Issue by wassimz** [viritin/viritin#43] opened 2015-01-08 07:54 UTC
Hi,

I have tried to implement a cross fields validation like the one described on this link https://dwuysan.wordpress.com/2012/03/20/cross-field-validation-using-bean-validation-jsr-303/

but this custom validator is not working. The form is not considering it.

Can any one help me to fix this. Notice that custom filter on single field works fine but not suitable to do cross field validation

**Comment by mstahv** [comment] 2015-01-08 10:32
Hi, I don't have that much experience with JSR 303 + cross field validation, but this sure sounds like an essential feature. Have you tried/checked if BeanFieldGroup works properly with cross field validation? If this works, we'd just need UI for it (displaying validation error). If it don't we could add support for it into MBeanFieldGroup.

Do you have some simple case for this? Start date before end date would be a simple and easily understandable example?

**Comment by KelibiaPort** [comment] 2015-01-08 10:45
Thanks for replies. I haven't tested before with the BeanFieldGroup. Currently I am testing it with a form having start and end time getting for PopupfieldDate field. I will try to create a small project to illustrate this issue.

Thanks

**Comment by KelibiaPort** [comment] 2015-03-31 21:06
Any updates on this features. Still not able to integrate it
:(

Any hints ?

**Comment by mstahv** [comment] 2015-03-31 21:10
Hi, I think the issue is still just valid. I just have quite limited resources to invest to this add-on. And also a better approach would be to get proper cross field validation support to Vaadin core. [This](http://dev.vaadin.com/ticket/8096) is one of our most voted issues.

**Comment by KelibiaPort** [comment] 2015-04-06 06:52
Thanks for you reply.

I have also tried to test it using method annotation but this does not work.

I think this is due to that vaadin form binding are validating only annotated property and it is using the beanValidator class (https://github.com/vaadin/vaadin/blob/master/server/src/com/vaadin/data/validator/BeanValidator.java). where we can see that only class property are validated.

So my question is Can we append another validator class to the viritin form so we can extend these bean validation methods ??

Thanks for helps

**Comment by mstahv** [comment] 2015-05-30 00:17
Finally started working on this. The master branch now has a basic support for programmatic cross field validators. See https://github.com/viritin/viritin/blob/master/src/test/java/org/vaadin/viritin/it/CrossFieldValidation.java

I haven't yet worked on it at all, but I'd guess it should now be fairly easy to add also JSR 303 checks for the bean level as well. Logic related to it should go somewhere here: https://github.com/viritin/viritin/blob/1477dd85ffb1b63ab2b2a4da30d91fd7e5087211/src/main/java/org/vaadin/viritin/MBeanFieldGroup.java#L240-L261

**Comment by mstahv** [comment] 2015-05-30 20:14
The master branch now contains an implementation that I'm pretty happy with. It now supports both programmatic validators, which can be bound to specific fields or left as generic bean level validations, or JSR303 style cross field validators (always "bean level"). Bean level errors can be fetched with MFieldGroup.getBeanLevelValidationErrors().

I'll still add a mechanism to AbstractForm to show cross field validation errors easily, something like what is currently hacked in https://github.com/viritin/viritin/blob/c6e113be291aaff82dda1705a8880e10c0610e92/src/test/java/org/vaadin/viritin/it/CrossFieldValidation.java#L142-L155.

Then a release to get early feedback? Pretty large renewals but I hope I haven't broken anything.

**Comment by KelibiaPort** [comment] 2015-05-31 08:28
Hi,

Thanks a lot for this support. It's great and it's works like a charm :)
I have tested right now (following same provided test file) and it seems not broking anything (for the momnt :+1: )

**Comment by mstahv** [comment] 2015-05-31 08:31
Thanks for your early test! Makes me more confident to release it early. I'll probably give this a fresh look  today evening or tomorrow and build a release if I'm still happy with the solution.

**Comment by KelibiaPort** [comment] 2015-05-31 08:34
One thing will be great if it is possible to propagate validation message directly to field error tooltip instead of displaying in a separate Field (like the RichText field as in the test file).

**Comment by mstahv** [comment] 2015-05-31 08:44
With JSR303 style cross field validators it is pretty hard to figure out a generic method on which field the validation message should be assigned. Maybe a method like this?

    /**
     * Sets to component to which bean level validation messages are attached in UI.
     */
    setCrossFieldValidationTarget(Component c)

That could be an alternative method to handle errors in addition to some domain specific mechanism like what it currently setup for the test case. The problem there is that you might have several bean level validators, so you might need  a version with a validator class as well.

**Comment by KelibiaPort** [comment] 2015-05-31 10:39
Hi,

I have faced a new issue after updating viritin addon. I had a EnumSelect field that is bind to an Enum field. Now when I change the state of that field, I got this exception:

java.lang.NullPointerException
	at org.vaadin.viritin.MBeanFieldGroup.valueChange(MBeanFieldGroup.java:226) [viritin-1.34-SNAPSHOT.jar:1.34-SNAPSHOT]


I don't know if it is related or not, but it was working fine before updating the addon. 
Thanks for helping

**Comment by mstahv** [comment] 2015-05-31 10:50
I added a null check, but I think there is actually a small issue in TypedSelect (that EnumSelect inherits). The value change listeners it hooks to the actual implementation should be "piggypacked" so that the property is reported to be the TypedSelect instance instead of the wrapped one.

**Comment by KelibiaPort** [comment] 2015-05-31 11:15
Yes right I was debugging it and it seems that the EnumSelect is not find once getting it from propertyIdToField HashMap on class FieldGroup. 

The fix seems to work now (i have tested and no more exception throws)

Thanks

**Comment by mstahv** [comment] 2015-07-09 19:15
I assume this can now be closed as fixed.

**Closed by mstahv** 2015-07-09 19:15 UTC
